### ISSUE TITLE
[Feature] User Entity Migration

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend_v2#20]
## Title

- [Feature] User Entity Migration

## Description

- 유저 테이블에  프로필 이미지 주소를 넣을 수 있는 Column 필요
- 유저 테이블에 연락처를 저장할 수 있는 Column 필요

## TODO

- [ ] : 마이그레이션 파일 작성
- [ ] : User Entity 및 User Response 수정
- [ ] : 테스트 코드 수정

## Watch out 

- ToDo 외 다른 작업

**Comment by leewoooo** [comment]
Column을 추가하는 Migration을 추가하는 것이 아니라 기존 Migration 파일을 수정 후 변경 점 적용

**Comment by leewoooo** [comment]
already resolved with #22
