### ISSUE TITLE
[Feature] User Entity

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend_v2#4]
## Title

- [Feature] User Entity

## Description

- 모든 비지니스 로직의 중심이 되는 User Entity 정의

## TODO

- [x] : User Entity에 필요한 Column 정의 및 SQL문 작성하기
- [x] : Column 중 Enum을 적용시킬 수 있는 Column (Role, Rank, Gender)는 [ts-jenum](https://www.npmjs.com/package/ts-jenum)이용하기
- [x] : TypeORM Migration 세팅 후 User 테이블 생성하기

## Watch out 

- TODO 외 다른 작업
