### ISSUE TITLE
[Feature] Auth Module

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_backend_v2#6]
## Title

- [Feature] Auth Module

## Description

- 인증에 필요한 Auth Module 구현하기.

### Login

- 유저의 `Id`와 `Password`를 받아 로그인이 가능해야 하며 로그인이 성공적으로 완료 될 경우 JWT 토큰을 발급하여 `FrontEnd` 에 넘겨준다.
    - `TokenService`를 통해 Token을 생성하며 `AccessToken` 및 `RefreshToken` 을 생성하며 `RefreshToken`을 `refresh_tokens`테이블에 저장을 한다.
    - 토큰별로 토큰의 고유 ID를 가지고 있으며 uuid를 이용
    - 로그인은 User의 Role이 LEADER 이상일 때 가능하다.

- 로그인 시 발생할 수 있는 `Exception`은 다음과 같다
    - 로그인 하려는 유저가 존재하지 않는 경우 `NotFoundException`
    - 로그인 하려는 유저의 `Role` 이 적합하지 않는 경우 `BadRequestException`
    - 비밀번호가 일치하지 않는 경우 `UnAuthorizationException`

### Logout

- 유저의 `AccessToken`을 받아 해당 토큰이 유효한지 검증 후 `RefreshToken`을 삭제시킨다.
    - `TokenService`를 통해 Token을 검증 후 Token의 Claim을 이용하여 `RefreshToken`을 검색하여 삭제한다. (토큰의 uuid를 이용)

- 로그아웃 시 발생할 수 있는 `Exception` 은 다음과 같다.
    - 로그아웃은 별도의 `Exception` 발생이 없다. **토큰이 유효하지 않거나 `RefreshToken` 이 존재하지 않아도 서버 상 로그만 작성하고 return 한다.**

### Refresh

- 유저의 `AccessToken`을 받아 해당 토큰이 유효한지 검증 후  `RefreshToken`을 갱신시킨다.
    - `TokenService`를 통해 Token을 검증 후 Token의 Claim을 이용하여 새로운 `AccessToken`을 생성 후 FrontEnd에 넘겨준다. 이 때 `RefreshToken` 또한 새로 생성하여 재 사용을 방지한다.
    
- Refresh시 발생할 수 있는 `Exception` 은 다음과 같다.
    - DB에 Refresh Token이 존재하지 않는 경우 `NotFoundException`
    - AccessToken이 유효하지 않는 경우 `UnAuthorizationException`

- Refresh시 `Exception` 발생하면 `Frontend` 는 **라우터를 전부 종료하고 로그인 페이지로 이동 시켜야 한다.**

### Change Password (자기 자신의 비밀번호를 변경)

- 유저의 현재 비밀번호와 변경될 비밀번호를 요청으로 받아 비밀번호를 변경한다.
    - 요청으로는 아래와 같은 정보를 받게된다.
        - `AccessToken`, 이전 비밀번호, 변경될 비밀번호
    - `FrontEnd` 에서는 변경 될 비밀번호를 2번 입력받아 두 개의 값이 동일한지 확인 후 같지 않다면 `Form` 에서 **오류 메세지를 보여준다**

- 비밀번호를 변경할 때 발생할 수 있는 `Exception`은 다음과 같다.
    - `AccessToken` 을 통해 유저를 검색했을 때 유저가 존재하지 않는 경우 `NotFoundException`
    - 요청을 받은 이전 비밀번호가 현재 비밀번호와 다른 경우 `UnAuthorizationException`

## TODO

- [x] : Token Service interface 정의 및 impl 구현
- [x] : Token Service 테스트 코드 작성
- [x] : Refresh Token을 저장할 테이블 마이그레이션 스크립트 작성 및 Entity 정의
- [x] : Auth Service interface 정의 및  impl 구현
- [x] : Auth Service 테스트 코드 작성

## Watch out 

- TODO 외 다른 작업은 하지 않을 것
